version: '3.8'

services:
  leadgen-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadgen-comment-bot
    ports:
      - "3000:3000"
    environment:
      - LINKEDIN_USER=${LINKEDIN_USER}
      - LINKEDIN_PASS=${LINKEDIN_PASS}
      - YOUTUBE_USER=${YOUTUBE_USER}
      - YOUTUBE_PASS=${YOUTUBE_PASS}
      - PORT=${PORT:-3000}
      - NODE_ENV=production
    volumes:
      # Persist browser profiles to maintain login sessions
      - linkedin_profile:/app/linkedin_profile
      - youtube_profile:/app/youtube_profile
      - tiktok_profile:/app/tiktok_profile
    restart: unless-stopped
    # Security options for running Chrome in Docker
    cap_add:
      - SYS_ADMIN
    # Alternative to SYS_ADMIN if you want more security
    # security_opt:
    #   - seccomp=unconfined
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  linkedin_profile:
    driver: local
  youtube_profile:
    driver: local
  tiktok_profile:
    driver: local

