version: '3.8'

services:
  leadgen-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadgen-comment-bot
    ports:
      - "3000:3000"
      - "6080:6080"  # noVNC web interface for remote desktop access
    environment:
      - LINKEDIN_USER=${LINKEDIN_USER}
      - LINKEDIN_PASS=${LINKEDIN_PASS}
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - REDDIT_ACCESS_TOKEN=${REDDIT_ACCESS_TOKEN}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - X_CLIENT_ID=${X_CLIENT_ID}
      - X_CLIENT_SECRET=${X_CLIENT_SECRET}
      - TIKTOK_USER=${TIKTOK_USER}
      - TIKTOK_PASS=${TIKTOK_PASS}
      - PORT=${PORT:-3000}
      - TWITTER_USER=${TWITTER_USER}
      - TWITTER_PASS=${TWITTER_PASS}
      - NODE_ENV=production
    volumes:
      # Persist browser profiles to maintain login sessions
      - linkedin_profile:/app/linkedin_profile
      - youtube_profile:/app/youtube_profile
      - tiktok_profile:/app/tiktok_profile
      - reddit_profile:/app/reddit_profile
      - twitter_profile:/app/twitter_profile
    restart: unless-stopped
    # Security options for running Chrome in Docker
    cap_add:
      - SYS_ADMIN
    # Alternative to SYS_ADMIN if you want more security
    # security_opt:
    #   - seccomp=unconfined
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  linkedin_profile:
    driver: local
  youtube_profile:
    driver: local
  tiktok_profile:
    driver: local
  reddit_profile:
    driver: local
  twitter_profile:
    driver: local



